name: Hydra CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --color always

    - name: Unit Test
      run: cargo test --color always

  documentation:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Publish Docs
      run: | 
        cargo doc --no-deps
        rm -rf ./docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html
        cp -r target/doc ./docs